# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_API_KEY: ${{ secrets.DEPLOY_SERVER_DEPLOY_SH }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Put the Environments
      run: |
        mkdir ./src/main/resources/
        echo "${{ secrets.ENV }}" >> ./src/main/resources/config.properties

    - name: Build with Gradle
      # uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      # with:
        # arguments: build
      run: |
        gradle wrap
        ./gradlew wrapper
        ./gradlew clean build

    - name: Copy WAR to Deployment Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }} # SSH 키 사용
        source: build/libs/webapp.war
        target: ${{ secrets.DEPLOY_SERVER_WAR_PATH }}
        
    - name: SSH into Deployment Server
      uses: appleboy/ssh-action@master # SSH로 서버에 접속
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }} # 서버 호스트 주소
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }} # SSH 유저명
        key: ${{ secrets.DEPLOY_SSH_KEY }} # SSH 키 사용
        script: |
          $DEPLOY_SERVER_DEPLOY_SH
